name: le name
on:
  issues:
    types: [opened]
jobs:
  commentaire:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Réponse à une issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "Merci d'avoir ouvert cette issue."
